x-mm-common: &mm-common
  build: .
  restart: "no"
  stop_grace_period: 60s
  env_file:
    - .env
  volumes:
    - ./config.toml:/app/config.toml:ro
    - ./logs:/app/logs
  logging:
    driver: "json-file"
    options:
      max-size: "3m"
      max-file: "3"

services:
  mm-sol:
    <<: *mm-common
    command: SOL ${MM_ARGS:-}

  mm-btc:
    <<: *mm-common
    command: BTC ${MM_ARGS:-}

  mm-eth:
    <<: *mm-common
    command: ETH ${MM_ARGS:-}

  mm-hype:
    <<: *mm-common
    command: HYPE ${MM_ARGS:-}

  mm-xrp:
    <<: *mm-common
    command: XRP ${MM_ARGS:-}

  mm-sui:
    <<: *mm-common
    command: SUI ${MM_ARGS:-}
